title: Awesome Site Title
author: GitHub User
email: your-email@domain.com
description: >
  Awesome site description here

baseurl: "" # the subpath of your site, e.g. /blog
url: "http://yourdomain.com" # the base hostname & protocol for your site
paginate:	5 # The number of posts to show per page on your homepage

permalink: /blog/:year/:month/:day/:title/
category_dir: blog/categories

twitter_username: jekyllrb
github_username:  jekyll

markdown: kramdown
kramdown:
  parse_block_html: true

gems:
  - jekyll-paginate
