title: Awesome Site Title
author: GitHub User
email: your-email@domain.com
description: >
  Awesome site description here

baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site

twitter_username: jekyllrb

markdown: kramdown

google_analytics: ""
